use serde_json::{json, Value};
use std::fs;
use std::path::{Path, PathBuf};

/// The exact `sebenza-agentctl` Python helper.
const AGENTCTL_SCRIPT: &str = include_str!("testdata/sebenza-agentctl.py");

/// Every artifact Sebenza generates inside a worktree. All are git-excluded: they are
/// machine-local wiring, and committing them would ship executable code (a shell-invoking
/// hooks.json, or a JS plugin opencode loads in-process) to every teammate and CI runner
/// that checks out the branch.
const GENERATED_WORKTREE_ARTIFACTS: &[&str] = &[
    ".codex/hooks.json",
    ".opencode/plugins/",
    ".claude/settings.local.json",
];

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// `<agentctl> <subcommand>` command string for a hook entry.
fn cmd(agentctl: &str, sub: &str) -> String {
    format!("{} {sub}", shell_quote(agentctl))
}

fn claude_hook_settings(agentctl: &str) -> Value {
    json!({
        "UserPromptSubmit": [{"hooks": [{"type": "command", "command": cmd(agentctl, "claude-user-prompt-submit"), "async": true}]}],
        "Notification": [{"matcher": "permission_prompt|elicitation_dialog", "hooks": [{"type": "command", "command": cmd(agentctl, "status-changed --lifecycle idle"), "async": true}]}],
        "Stop": [{"hooks": [{"type": "command", "command": cmd(agentctl, "agent-stopped"), "async": true}]}],
        "PostToolUse": [
            {"hooks": [{"type": "command", "command": cmd(agentctl, "status-changed --lifecycle running"), "async": true}]},
            {"matcher": "Bash", "hooks": [{"type": "command", "command": cmd(agentctl, "claude-post-tool-use"), "async": true}]}
        ]
    })
}

fn codex_hook_settings(agentctl: &str) -> Value {
    json!({
        "SessionStart": [{"matcher": "startup|resume|clear", "hooks": [{"type": "command", "command": cmd(agentctl, "codex-session-start"), "timeout": 30}]}],
        "UserPromptSubmit": [{"hooks": [{"type": "command", "command": cmd(agentctl, "codex-user-prompt-submit"), "timeout": 30}]}],
        "PermissionRequest": [{"hooks": [{"type": "command", "command": cmd(agentctl, "codex-permission-request"), "timeout": 30}]}],
        "PreToolUse": [{"hooks": [{"type": "command", "command": cmd(agentctl, "status-changed --lifecycle running --best-effort"), "timeout": 30}]}],
        "PostToolUse": [{"matcher": "Bash", "hooks": [{"type": "command", "command": cmd(agentctl, "codex-post-tool-use"), "timeout": 30}]}],
        "Stop": [{"hooks": [{"type": "command", "command": cmd(agentctl, "codex-stop"), "timeout": 30}]}]
    })
}

/// The generated opencode plugin.
///
/// Constraints this satisfies deliberately:
/// - **imports nothing.** `~/.config/opencode` is an npm/bun package root, so importing
///   `@opencode-ai/plugin` would couple the file to module resolution inside the user's
///   config dir. `fetch` and the injected `$` are runtime globals under opencode's bundled
///   Bun, so no import is needed.
/// - **embeds no per-worktree literals.** The agentctl path arrives via `SEBENZA_AGENTCTL`
///   (exported into the pane's runtime env), and the worktree comes from opencode's own
///   `PluginInput`. That keeps the file byte-identical across worktrees so the
///   pre-launch integrity check can compare against one stored hash.
/// - **forwards derived signals only** — never raw `tool_input`, command text or output,
///   matching `sebenza-agentctl`'s existing discipline.
///
/// Event names are the verified wire values observed from a real session, not the SDK
/// class names: `session.created`, `session.idle`, `session.error`.
const OPENCODE_PLUGIN_JS: &str = r#"// Generated by Sebenza. Do not edit; regenerated on every worktree open.
// Git-excluded: this file is executed in-process by opencode.
export const SebenzaPlugin = async ({ $ }) => {
  const ctl = process.env.SEBENZA_AGENTCTL;
  const run = async (sub, payload) => {
    if (!ctl) return;
    try {
      const proc = $`${ctl} ${sub}`.stdin(JSON.stringify(payload ?? {}));
      await proc.quiet();
    } catch (_) {
      // Hook failures must never take the agent down.
    }
  };

  return {
    // Lifecycle. session.created carries the id Sebenza needs to correlate this
    // worktree to an opencode session without polling.
    event: async ({ event }) => {
      const type = event?.type;
      if (type === "session.created") {
        await run("opencode-session-created", { sessionID: event?.properties?.info?.id });
      } else if (type === "session.idle") {
        await run("opencode-stop", {});
      } else if (type === "session.error") {
        await run("runtime-error", { message: "opencode session error" });
      }
    },

    // Running/idle status and PR detection.
    "tool.execute.before": async () => {
      await run("opencode-tool-before", {});
    },
    "tool.execute.after": async (input, output) => {
      await run("opencode-tool-after", {
        tool_name: input?.tool,
        tool_input: output?.args ?? {},
      });
    },

    // Declared so the hook exists from the start; it currently only reports that a
    // permission was requested. Sebenza cannot yet DENY - whether the mutable status is
    // honoured is unproven (see the phase-3 spike), so the verdict is left untouched.
    "permission.ask": async () => {
      await run("opencode-permission-ask", {});
    },
  };
};
"#;

/// Write the agentctl helper + per-agent hook configs for a worktree.
pub fn ensure_agent_runtime_artifacts(git_dir: &str, worktree_path: &str) -> Result<(), String> {
    let sebenza_dir = Path::new(git_dir).join(".ai").join("sebenza");
    fs::create_dir_all(&sebenza_dir).map_err(|e| e.to_string())?;
    let agentctl_path = sebenza_dir.join("sebenza-agentctl");
    fs::write(&agentctl_path, AGENTCTL_SCRIPT).map_err(|e| e.to_string())?;
    set_executable(&agentctl_path);
    let agentctl = agentctl_path.to_string_lossy().to_string();

    let claude_settings = Path::new(worktree_path).join(".claude").join("settings.local.json");
    merge_claude_settings(&claude_settings, &claude_hook_settings(&agentctl))?;

    let codex_hooks = Path::new(worktree_path).join(".codex").join("hooks.json");
    merge_codex_hooks(&codex_hooks, &codex_hook_settings(&agentctl), &agentctl)?;

    // opencode: a Sebenza-owned single file, so it is overwritten wholesale rather than
    // merged - unlike the claude/codex configs, which live in files the user also owns.
    let opencode_plugin = Path::new(worktree_path)
        .join(".opencode")
        .join("plugins")
        .join("sebenza.js");
    if let Some(parent) = opencode_plugin.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    fs::write(&opencode_plugin, OPENCODE_PLUGIN_JS).map_err(|e| e.to_string())?;

    ensure_generated_artifacts_ignored(git_dir)?;
    Ok(())
}

fn read_json_object(path: &Path) -> serde_json::Map<String, Value> {
    fs::read_to_string(path)
        .ok()
        .and_then(|raw| serde_json::from_str::<Value>(&raw).ok())
        .and_then(|v| v.as_object().cloned())
        .unwrap_or_default()
}

fn write_json(path: &Path, value: &Value) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let json = serde_json::to_string_pretty(value).map_err(|e| e.to_string())?;
    fs::write(path, format!("{json}\n")).map_err(|e| e.to_string())
}

/// Claude: our hook events overwrite same-named events, other keys preserved.
fn merge_claude_settings(path: &Path, hooks: &Value) -> Result<(), String> {
    let mut existing = read_json_object(path);
    let mut merged_hooks = existing
        .get("hooks")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    if let Some(hooks_obj) = hooks.as_object() {
        for (k, v) in hooks_obj {
            merged_hooks.insert(k.clone(), v.clone());
        }
    }
    existing.insert("hooks".to_string(), Value::Object(merged_hooks));
    write_json(path, &Value::Object(existing))
}

fn command_starts_with_agentctl(command: &str, agentctl: &str) -> bool {
    let c = command.trim_start();
    let quoted = shell_quote(agentctl);
    c == agentctl
        || c.starts_with(&format!("{agentctl} "))
        || c == quoted
        || c.starts_with(&format!("{quoted} "))
}

fn is_sebenza_hook_group(group: &Value, agentctl: &str) -> bool {
    group
        .get("hooks")
        .and_then(Value::as_array)
        .map(|hooks| {
            hooks.iter().any(|h| {
                h.get("command")
                    .and_then(Value::as_str)
                    .map(|c| command_starts_with_agentctl(c, agentctl))
                    .unwrap_or(false)
            })
        })
        .unwrap_or(false)
}

/// Codex: per event, drop prior Sebenza groups and append the fresh ones.
fn merge_codex_hooks(path: &Path, hooks: &Value, agentctl: &str) -> Result<(), String> {
    let mut existing = read_json_object(path);
    let existing_hooks = existing.get("hooks").and_then(Value::as_object).cloned().unwrap_or_default();
    let mut merged = existing_hooks.clone();
    if let Some(hooks_obj) = hooks.as_object() {
        for (event, groups) in hooks_obj {
            let mut preserved: Vec<Value> = existing_hooks
                .get(event)
                .and_then(Value::as_array)
                .map(|arr| arr.iter().filter(|g| !is_sebenza_hook_group(g, agentctl)).cloned().collect())
                .unwrap_or_default();
            if let Some(new_groups) = groups.as_array() {
                preserved.extend(new_groups.iter().cloned());
            }
            merged.insert(event.clone(), Value::Array(preserved));
        }
    }
    existing.insert("hooks".to_string(), Value::Object(merged));
    write_json(path, &Value::Object(existing))
}

fn resolve_git_common_dir(git_dir: &str) -> PathBuf {
    match fs::read_to_string(Path::new(git_dir).join("commondir")) {
        Ok(content) => {
            let trimmed = content.trim();
            if trimmed.is_empty() {
                PathBuf::from(git_dir)
            } else if trimmed.starts_with('/') {
                PathBuf::from(trimmed)
            } else {
                Path::new(git_dir).join(trimmed)
            }
        }
        Err(_) => PathBuf::from(git_dir),
    }
}

/// Add every generated in-worktree artifact to the repo's `info/exclude`, idempotently.
fn ensure_generated_artifacts_ignored(git_dir: &str) -> Result<(), String> {
    let exclude_path = resolve_git_common_dir(git_dir).join("info").join("exclude");
    let existing = fs::read_to_string(&exclude_path).unwrap_or_default();
    let missing: Vec<&str> = GENERATED_WORKTREE_ARTIFACTS
        .iter()
        .copied()
        .filter(|p| !existing.lines().any(|l| l.trim() == *p))
        .collect();
    if missing.is_empty() {
        return Ok(());
    }
    if let Some(parent) = exclude_path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let separator = if !existing.is_empty() && !existing.ends_with('\n') { "\n" } else { "" };
    let added = missing.join("\n");
    fs::write(&exclude_path, format!("{existing}{separator}{added}\n")).map_err(|e| e.to_string())
}

#[cfg(unix)]
fn set_executable(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    let _ = fs::set_permissions(path, fs::Permissions::from_mode(0o755));
}

#[cfg(not(unix))]
fn set_executable(_path: &Path) {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::util::id::random_hex;


    #[test]
    fn opencode_plugin_is_import_free_and_byte_stable_across_worktrees() {
        let base = std::env::temp_dir().join(format!("sebenza-oc-{}", random_hex(4)));
        let mut written = Vec::new();
        for name in ["wt-a", "wt-b"] {
            let git_dir = base.join(name).join("git");
            let wt = base.join(name).join("wt");
            fs::create_dir_all(&git_dir).unwrap();
            fs::create_dir_all(&wt).unwrap();
            ensure_agent_runtime_artifacts(
                &git_dir.to_string_lossy(),
                &wt.to_string_lossy(),
            )
            .unwrap();
            let plugin = wt.join(".opencode").join("plugins").join("sebenza.js");
            let body = fs::read_to_string(&plugin).expect("opencode plugin written");
            written.push(body);
        }

        let js = &written[0];
        // Import-free: `~/.config/opencode` is an npm/bun package root, so importing
        // @opencode-ai/plugin would couple the generated file to module resolution.
        assert!(!js.contains("import "), "generated plugin must not import anything:\n{js}");
        assert!(!js.contains("require("), "generated plugin must not require anything");
        // Byte-stable across worktrees, so the integrity check can compare a stored hash
        // without every worktree looking different.
        assert_eq!(written[0], written[1], "plugin must not embed per-worktree literals");
        // No absolute paths baked in.
        assert!(!js.contains(&base.to_string_lossy().to_string()), "no worktree paths inline");

        // Hooks Sebenza depends on, per the verified event names.
        for needle in [
            "permission.ask",
            "tool.execute.before",
            "tool.execute.after",
            "session.created",
            "session.idle",
            "session.error",
        ] {
            assert!(js.contains(needle), "plugin must handle {needle}:\n{js}");
        }
        // It must reach agentctl via env, not a compiled-in path.
        assert!(js.contains("SEBENZA_AGENTCTL"), "agentctl path must come from the env");

        fs::remove_dir_all(&base).ok();
    }

    #[test]
    fn generated_plugin_paths_are_git_excluded() {
        let base = std::env::temp_dir().join(format!("sebenza-excl-{}", random_hex(4)));
        let git_dir = base.join("git");
        let wt = base.join("wt");
        fs::create_dir_all(&git_dir).unwrap();
        fs::create_dir_all(&wt).unwrap();
        ensure_agent_runtime_artifacts(&git_dir.to_string_lossy(), &wt.to_string_lossy()).unwrap();

        let exclude = fs::read_to_string(git_dir.join("info").join("exclude")).unwrap();
        for path in [".codex/hooks.json", ".opencode/plugins/", ".claude/settings.local.json"] {
            assert!(
                exclude.lines().any(|l| l.trim() == path),
                "{path} must be git-excluded; got:\n{exclude}"
            );
        }
        fs::remove_dir_all(&base).ok();
    }

    #[test]
    fn writes_agentctl_and_hooks_idempotently() {
        let base = std::env::temp_dir().join(format!("sebenza-artifacts-{}", random_hex(4)));
        let git_dir = base.join("git");
        let wt = base.join("wt");
        fs::create_dir_all(&git_dir).unwrap();
        fs::create_dir_all(&wt).unwrap();
        let git_dir = git_dir.to_string_lossy().to_string();
        let wt = wt.to_string_lossy().to_string();

        ensure_agent_runtime_artifacts(&git_dir, &wt).unwrap();

        // agentctl written verbatim.
        let ctl = fs::read_to_string(Path::new(&git_dir).join(".ai").join("sebenza").join("sebenza-agentctl")).unwrap();
        assert!(ctl.starts_with("#!/usr/bin/env python3"));
        assert_eq!(ctl, AGENTCTL_SCRIPT);

        let claude: Value = serde_json::from_str(
            &fs::read_to_string(Path::new(&wt).join(".claude").join("settings.local.json")).unwrap(),
        )
        .unwrap();
        let stop_cmd = claude["hooks"]["Stop"][0]["hooks"][0]["command"].as_str().unwrap();
        assert!(stop_cmd.contains("agent-stopped"));

        let codex: Value = serde_json::from_str(
            &fs::read_to_string(Path::new(&wt).join(".codex").join("hooks.json")).unwrap(),
        )
        .unwrap();
        assert!(codex["hooks"]["SessionStart"].is_array());

        // Re-running must not duplicate the Sebenza codex hook groups.
        ensure_agent_runtime_artifacts(&git_dir, &wt).unwrap();
        let codex2: Value = serde_json::from_str(
            &fs::read_to_string(Path::new(&wt).join(".codex").join("hooks.json")).unwrap(),
        )
        .unwrap();
        assert_eq!(codex2["hooks"]["Stop"].as_array().unwrap().len(), 1);

        // The generated codex hooks file is git-excluded.
        let exclude = fs::read_to_string(Path::new(&git_dir).join("info").join("exclude")).unwrap();
        assert!(exclude.contains(".codex/hooks.json"));

        fs::remove_dir_all(&base).ok();
    }
}
